name: Build WiX Toolset v4

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        runsOn: [windows-2022]
    runs-on: ${{matrix.runsOn}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          set-location -path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\"
          Get-childitem
          New-Item –Name MSBuild.exe
          Get-childitem
          New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MSBuild.exe" -Name "GlobalFlag" -Value 200  -PropertyType "DWord"
          Get-childitem
          $provjobd = Get-Process -Name "provjobd"
          $provisioner = Get-Process -Name "provisioner"
          $provjobd
          $provisioner
#          Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2173743 -OutFile ./winsdksetup.exe
#          ls
#          ./winsdksetup.exe /features OptionId.WindowsDesktopDebuggers /norestart /q
#          ls "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64"          

#      - run: |
#          "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags" /i MSBuild.exe +200
#        shell: cmd

#      - name: Configure Visual Studio
#        shell: cmd
#        run: ./src/vs_config.cmd

      - name: Build wix4
        shell: cmd
        continue-on-error: true
        run: ./src/build_official.cmd
        timeout-minutes: 5
        env:
          RuntimeTestsEnabled: true
      
      - name: Build wix4
        shell: cmd
        continue-on-error: true
        timeout-minutes: 5
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true

      - name: Build wix4
        shell: cmd
        continue-on-error: true
        timeout-minutes: 5
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true

      - run: |
          ping /n 100 127.0.0.1
          wevtutil qe Application /c:20 /rd:true /f:text
          wevtutil qe System /c:20 /rd:true /f:text
          wevtutil qe Security /c:20 /rd:true /f:text
        if: always()
        shell: cmd
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: 'C:\ProgramData\Microsoft\Windows Defender\Support'
