name: Build WiX Toolset v4

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          Clear-EventLog -LogName application, system

      - name: Configure Visual Studio
        shell: cmd
        run: ./src/vs_config.cmd

      - name: Build wix4
        shell: cmd
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true
      
      - run: |
          Write-Host Applog
          Get-EventLog -LogName application -Newest 100
          Write-Host Syslog
          Get-EventLog -LogName system -Newest 100
          Write-Host Applog
          Get-EventLog -LogName application -Newest 100 | Select-Object -Property Source, EventID, InstanceId, Message
          Write-Host Syslog
          Get-EventLog -LogName system -Newest 100 | Select-Object -Property Source, EventID, InstanceId, Message 
        if: always()
